import type { NextPage } from "next";
import Head from "next/head";

import { signIn, useSession } from "next-auth/react";
import ProjectsList from "../components/ProjectsList";
import UserCard from "../components/UserCard";

import { MdNoteAdd } from "react-icons/md";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Personal projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto lg:flex lg:flex-col items-center justify-center h-screen p-4">
        <h1 className="lg:py-12 text-3xl md:text-[5rem] lg:text-5xl leading-normal font-extrabold text-gray-700">
          Personal <span className="text-purple-300">Projects</span> App
        </h1>

        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full pb-4">
          {session ? (
            <div className="flex flex-col lg:flex-row w-full h-full">
              <UserCard {...session} />
              <div className="py-4 lg:py-0 w-full h-full">
                <ProjectsList userId={session.user!.id!} />
              </div>
              <a
                href="/projects/new"
                className="border border-gray-500 h-full w-full md:w-96 md:h-64 lg:w-1/2 lg:h-full self-center text-white px-3 py-3 rounded-md bg-gray-100 transition hover:bg-gray-300 focus:bg-gray-200 active:bg-gray-300 flex justify-center items-center"
              >
                <MdNoteAdd size={128} color="black" />
              </a>
            </div>
          ) : (
            <button
              onClick={() => signIn("discord")}
              className="text-white px-3 py-3 rounded-md bg-sky-500 transition hover:bg-sky-600 focus:bg-sky-600 active:bg-sky-800"
            >
              Login with Discord
            </button>
          )}
        </div>
      </main>
    </>
  );
};

const LogCard = ({ name, description, documentation }: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};

export default Home;
