import type { NextPage } from "next";
import Head from "next/head";

import { signIn, useSession } from "next-auth/react";
import ProjectsList from "../components/ProjectsList";
import UserCard from "../components/UserCard";

import Link from "next/link";
import { MdNoteAdd } from "react-icons/md";
import Search from "../components/Search";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Personal projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto lg:flex lg:flex-col items-center justify-center h-screen p-4">
        <h1 className="lg:py-12 text-3xl md:text-[4rem] lg:text-5xl leading-normal font-extrabold text-gray-700 text-center">
          Personal <span className="text-purple-300">projects</span> App
        </h1>

        <Search />

        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full pb-4">
          {session ? (
            <div className="flex flex-col lg:flex-row w-full h-full space-y-8 lg:space-y-0">
              <UserCard
                id={session.user?.id}
                image={session.user?.image}
                name={session.user?.name || "anonymous"}
                email={session.user?.email}
              />

              <ProjectsList userId={session.user!.id!} />

              <Link href="/projects/new">
                <a className="border border-gray-500 h-full w-full md:w-96 md:h-64 lg:w-1/2 lg:h-full self-center text-white px-3 py-3 rounded-md bg-gray-100 transition hover:bg-gray-300 focus:bg-gray-200 active:bg-gray-300 flex justify-center items-center">
                  <MdNoteAdd size={128} color="black" />
                </a>
              </Link>
            </div>
          ) : (
            <button
              onClick={() => signIn("discord")}
              className="text-white px-3 py-3 rounded-md bg-sky-500 transition hover:bg-sky-600 focus:bg-sky-600 active:bg-sky-800"
            >
              Login with Discord
            </button>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
