import {
  AlertDialog,
  AlertDialogBody,
  AlertDialogContent,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogOverlay,
  Button,
  useDisclosure,
  useToast,
} from "@chakra-ui/react";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { FC, useEffect, useRef } from "react";
import { Resolver, useForm } from "react-hook-form";
import { inferMutationInput, trpc } from "../../utils/trpc";

type FormValues = inferMutationInput<"projects.create">;

const resolver: Resolver<FormValues> = async (values) => {
  return {
    values: values,
    errors: !values.title
      ? {
          title: {
            type: "required",
            message: "This is required.",
          },
        }
      : {},
  };
};

const NewProject: FC = () => {
  const { data: session, status } = useSession();

  const { isOpen, onOpen, onClose } = useDisclosure();
  const cancelRef = useRef<HTMLButtonElement>(null);

  const toast = useToast();

  const newProjectMutation = trpc.useMutation(["projects.create"]);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<FormValues>({ resolver });

  const handleCreate = async (e: FormValues) => {
    await newProjectMutation.mutateAsync({ ...e });
    toast({
      title: "Project created 🎉",
      description: "The project has been created succesfully.",
      status: "success",
      duration: 9000,
      isClosable: true,
    });
    reset();
  };

  useEffect(() => {
    if (!session?.user && status === "unauthenticated") {
      onOpen();
    }
  }, [session, status, onOpen]);

  return (
    <>
      <Head>
        <title>Personal Projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AlertDialog
        isOpen={isOpen}
        leastDestructiveRef={cancelRef}
        onClose={onClose}
      >
        <AlertDialogOverlay>
          <AlertDialogContent>
            <AlertDialogHeader fontSize="lg" fontWeight="bold">
              Unauthorized
            </AlertDialogHeader>

            <AlertDialogBody>
              In order to create projects you need to be logged in.
            </AlertDialogBody>

            <AlertDialogFooter>
              <Button ref={cancelRef} onClick={onClose}>
                Close
              </Button>
              <Button
                colorScheme="blue"
                onClick={() => signIn("discord")}
                ml={3}
              >
                Login
              </Button>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialogOverlay>
      </AlertDialog>

      <main className="container mx-auto lg:flex lg:flex-col items-center justify-center h-screen p-4">
        <h1 className="lg:py-12 text-3xl md:text-[4rem] lg:text-5xl leading-normal font-extrabold text-gray-700 text-center">
          Personal <span className="text-purple-300">projects</span> App
        </h1>
        <p className="text-gray-700 text-xl">Add a new project</p>

        <form
          className="mt-8 max-w-md pb-4"
          onSubmit={handleSubmit(handleCreate)}
        >
          <div className="grid grid-cols-1 gap-6">
            <label className="block">
              <span className="text-gray-700">Title</span>
              <input
                {...register("title")}
                id="title"
                type="text"
                className="mt-1 block w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
                placeholder="My cool project"
                disabled={!session?.user}
              />
            </label>
            <label className="block">
              <span className="text-gray-700">Slug</span>
              <input
                {...register("slug")}
                id="slug"
                type="text"
                className="mt-1 block w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
                placeholder="my-cool-project"
                disabled={!session?.user}
              />
            </label>
            <label className="block">
              <span className="text-gray-700">Logo URL</span>
              <input
                {...register("logo")}
                id="logo"
                type="text"
                className="mt-1 block w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
                placeholder="https://i.pinimg.com/originals/3e/70/6d/3e706db922d0562218c1a15b05427e2a.png"
                disabled={!session?.user}
              />
            </label>
            <label className="block">
              <span className="text-gray-700">Cover Image</span>
              <input
                {...register("coverImage")}
                id="coverImage"
                type="text"
                className="mt-1 block w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
                placeholder="https://c4.wallpaperflare.com/wallpaper/965/883/624/manga-one-piece-wallpaper-preview.jpg"
                disabled={!session?.user}
              />
            </label>
            <label className="block">
              <span className="text-gray-700">External URL</span>
              <input
                {...register("externalUrl")}
                id="externalUrl"
                type="text"
                className="mt-1 block w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
                placeholder="https://github.com/system32uwu/smart-pirates"
                disabled={!session?.user}
              />
            </label>

            <label className="block">
              <span className="text-gray-700">Description</span>
              <textarea
                {...register("fullDescription")}
                id="fullDescription"
                disabled={!session?.user}
                className="mt-1 block w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
                rows={3}
              ></textarea>
            </label>
          </div>
          <button
            disabled={!session?.user}
            type="submit"
            className="p-2 bg-gray-300 rounded-sm mt-2 w-full"
          >
            Create
          </button>
        </form>
      </main>
    </>
  );
};

export default NewProject;
